### ISSUE TITLE
Run mantlev2 use docker but wrong

### ISSUE THREAD

**Issue by orange723** [mantlenetworkio/networks#105]
How to fix this wrong，I find a doc [run-node-mainnetv2.md](https://github.com/mantlenetworkio/networks/blob/main/run-node-mainnetv2.md)

docker-compose.yml copy this change [docker-compose-mainnetv2.yml](https://github.com/mantlenetworkio/networks/blob/main/docker-compose-mainnetv2.yml)

docker-compose.yml

```
version: '3.4'

x-healthcheck: &healthcheck
  test: [ "CMD", "curl", "-sf", "http://localhost:8545" ]
  interval: 5s
  timeout: 5s
  retries: 3
  start_period: 30s

services:
  op-geth:
    image: mantlenetworkio/op-geth:v1.0.0-alpha.4
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8000M
        reservations:
          cpus: '4'
          memory: 8000M
      restart_policy:
        condition: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: geth
    command:
      - --datadir=/db
      - --verbosity=3
      - --port=30303
      - --http
      - --http.corsdomain=*
      - --http.vhosts=*
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.api=web3,eth,debug,txpool,net
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.origins=*
      - --ws.api=web3,eth,debug,txpool,net
      - --syncmode=full
      - --maxpeers=0
      - --networkid=5000
      - --rpc.allow-unprotected-txs
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/secret/jwt_secret_txt
      - --gcmode=archive
      - --metrics
      - --metrics.addr=0.0.0.0
      - --metrics.port=6060
      - --snapshot=false
      - --rollup.sequencerhttp=https://rpc.mantle.xyz
    volumes:
      - ./jwt_secret_txt:/secret/jwt_secret_txt
      - ./data-geth:/db
    ports:
      - 8545:8545
      - 8546:8546
      - 8551:8551
      - 6060:6060
      - 30303:30303
  op-node:
    image: mantlenetworkio/op-node:v1.0.0-alpha.3
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8000M
        reservations:
          cpus: '4'
          memory: 8000M
      restart_policy:
        condition: on-failure
    depends_on:
      - op-geth
    volumes:
      - ./jwt_secret_txt:/secret/jwt_secret_txt
      - ./p2p_node_key_txt:/secret/p2p_node_key_txt
      - ./mainnet/rollup.json:/config/rollup.json
      - ./mainnet/genesis.json:/config/genesis.json
      - ./data-node-peer:/op-node/opnode_peerstore_db
      - ./data-node-discovery:/op-node/opnode_discovery_db
    environment:
      OP_NODE_L1_ETH_RPC: 'https://rpc.ankr.com/eth'
      OP_NODE_L2_ENGINE_RPC: 'http://op-geth:8551'
      OP_NODE_L2_ENGINE_AUTH: /secret/jwt_secret_txt
      OP_NODE_ROLLUP_CONFIG: '/config/rollup.json'
      OP_NODE_P2P_PRIV_PATH: /secret/p2p_node_key_txt
      OP_NODE_VERIFIER_L1_CONFS: '3'
      OP_NODE_RPC_ADDR: '0.0.0.0'
      OP_NODE_RPC_PORT: 8545
      OP_NODE_P2P_LISTEN_IP: '0.0.0.0'
      OP_NODE_P2P_LISTEN_TCP_PORT: 9003
      OP_NODE_P2P_LISTEN_UDP_PORT: 9003
      OP_NODE_P2P_PEER_SCORING: 'light'
      OP_NODE_P2P_PEER_BANNING: 'true'
      OP_NODE_METRICS_ENABLED: 'true'
      OP_NODE_METRICS_ADDR: '0.0.0.0'
      OP_NODE_METRICS_PORT: 7300
      OP_NODE_PPROF_ENABLED: 'true'
      OP_NODE_PPROF_PORT: 6060
      OP_NODE_PPROF_ADDR: '0.0.0.0'
      OP_NODE_P2P_DISCOVERY_PATH: '/op-node/opnode_discovery_db'
      OP_NODE_P2P_PEERSTORE_PATH: '/op-node/opnode_peerstore_db'
      OP_NODE_INDEXER_SOCKET: 'da-indexer-api.mantle.xyz:80'
      OP_NODE_INDEXER_ENABLE: 'true'
      OP_NODE_L2_BACKUP_UNSAFE_SYNC_RPC: https://rpc.mantle.xyz
      OP_NODE_P2P_STATIC: '/dns4/peer0.mantle.xyz/tcp/9003/p2p/16Uiu2HAmKVKzUAns2gLhZAz1PYcbnhY3WpxNxUZYeTN1x29tNBAW,/dns4/peer1.mantle.xyz/tcp/9003/p2p/16Uiu2HAm1AiZtVp8f5C8LvpSTAXC6GtwqAVKnB3VLawWYSEBmcFN,/dns4/peer2.mantle.xyz/tcp/9003/p2p/16Uiu2HAm2UHVKiPXpovs8VbbUQVPr7feBAqBJdFsH1z5XDiLEvHT'
      OP_NODE_SEQUENCER_ENABLED: 'false'
      OP_NODE_P2P_AGENT: 'mantle'
      OP_NODE_L2_ENGINE_SYNC_ENABLED: 'true'
      OP_NODE_L2_SKIP_SYNC_START_CHECK: 'true'
      OP_NODE_P2P_SYNC_REQ_RESP: 'true'
    ports:
      - 9545:8545
```

log output

```
op-node_1  | t=2024-10-18T05:47:04+0000 lvl=eror msg="Unable to create the rollup node"   error="incorrect L2 RPC chain id, expected from config 5000, obtained from client 1"
op-node_1  | t=2024-10-18T05:47:04+0000 lvl=crit msg="Application failed"                 message="incorrect L2 RPC chain id, expected from config 5000, obtained from client 1"
mantle_op-node_1 exited with code 1
```

**Comment by johnnyji-dev** [comment]
how can you solve the issue?

**Comment by orange723** [comment]
> how can you solve the issue? [@orange723](https://github.com/orange723)

Sorry I forget it 

This compose file run mantlev2 full node is success right now, try this

replace OP_NODE_L1_ETH_RPC your eth rpc

```
version: '3.4'

x-healthcheck: &healthcheck
  test: [ "CMD", "curl", "-sf", "http://localhost:8545" ]
  interval: 5s
  timeout: 5s
  retries: 3
  start_period: 30s

services:
  op-geth:
    image: mantlenetworkio/op-geth:v1.0.0-alpha.4
    deploy:
      restart_policy:
        condition: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: geth
    command:
      - --datadir=/db
      - --verbosity=3
      - --port=30303
      - --http
      - --http.corsdomain=*
      - --http.vhosts=*
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.api=web3,eth,debug,txpool,net
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8545
      - --ws.origins=*
      - --ws.api=web3,eth,debug,txpool,net
      - --syncmode=full
      - --maxpeers=0
      - --networkid=5000
      - --rpc.allow-unprotected-txs
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/secret/jwt_secret_txt
      - --gcmode=archive
      - --metrics
      - --metrics.addr=0.0.0.0
      - --metrics.port=6060
      - --snapshot=false
      - --rollup.sequencerhttp=https://rpc.mantle.xyz
    volumes:
      - ./mainnet/genesis.json:/genesis.json
      - ./jwt_secret_txt:/secret/jwt_secret_txt
      - ./data-geth:/db
    ports:
      - 8545:8545
      - 8551:8551
      - 6060:6060
      - 30303:30303
   
  op-node:
    image: mantlenetworkio/op-node:v1.0.0-alpha.3
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - op-geth
    volumes:
      - ./jwt_secret_txt:/secret/jwt_secret_txt
      - ./p2p_node_key_txt:/secret/p2p_node_key_txt
      - ./mainnet/rollup.json:/config/rollup.json
      - ./data-node-peer:/op-node/opnode_peerstore_db
      - ./data-node-discovery:/op-node/opnode_discovery_db
    environment:
      OP_NODE_L1_ETH_RPC: YOUR_ETH_RPC use ws protocol
      OP_NODE_L2_ENGINE_RPC: 'http://op-geth:8551'
      OP_NODE_L2_ENGINE_AUTH: /secret/jwt_secret_txt
      OP_NODE_ROLLUP_CONFIG: '/config/rollup.json'
      OP_NODE_P2P_PRIV_PATH: /secret/p2p_node_key_txt
      OP_NODE_VERIFIER_L1_CONFS: '3'
      OP_NODE_RPC_ADDR: '0.0.0.0'
      OP_NODE_RPC_PORT: 8545
      OP_NODE_P2P_LISTEN_IP: '0.0.0.0'
      OP_NODE_P2P_LISTEN_TCP_PORT: 9003
      OP_NODE_P2P_LISTEN_UDP_PORT: 9003
      OP_NODE_P2P_PEER_SCORING: 'light'
      OP_NODE_P2P_PEER_BANNING: 'true'
      OP_NODE_METRICS_ENABLED: 'true'
      OP_NODE_METRICS_ADDR: '0.0.0.0'
      OP_NODE_METRICS_PORT: 7300
      OP_NODE_PPROF_ENABLED: 'true'
      OP_NODE_PPROF_PORT: 6060
      OP_NODE_PPROF_ADDR: '0.0.0.0'
      OP_NODE_P2P_DISCOVERY_PATH: '/op-node/opnode_discovery_db'
      OP_NODE_P2P_PEERSTORE_PATH: '/op-node/opnode_peerstore_db'
      OP_NODE_INDEXER_SOCKET: 'da-indexer-api.mantle.xyz:80'
      OP_NODE_INDEXER_ENABLE: 'true'
      OP_NODE_L2_BACKUP_UNSAFE_SYNC_RPC: https://rpc.mantle.xyz
      OP_NODE_P2P_STATIC: '/dns4/peer0.mantle.xyz/tcp/9003/p2p/16Uiu2HAmKVKzUAns2gLhZAz1PYcbnhY3WpxNxUZYeTN1x29tNBAW,/dns4/peer1.mantle.xyz/tcp/9003/p2p/16Uiu2HAm1AiZtVp8f5C8LvpSTAXC6GtwqAVKnB3VLawWYSEBmcFN,/dns4/peer2.mantle.xyz/tcp/9003/p2p/16Uiu2HAm2UHVKiPXpovs8VbbUQVPr7feBAqBJdFsH1z5XDiLEvHT'
      OP_NODE_SEQUENCER_ENABLED: 'false'
      OP_NODE_P2P_AGENT: 'mantle'
      OP_NODE_L2_ENGINE_SYNC_ENABLED: 'true'
      OP_NODE_L2_SKIP_SYNC_START_CHECK: 'true'
      OP_NODE_P2P_SYNC_REQ_RESP: 'true'
    ports:
      - 9545:8545
 ```
